server.port=8075
spring.application.name=xml-signature-demo

spring.datasource.url=jdbc:oracle:thin:@//37.187.250.163:1521/orclpdb1
spring.datasource.username=ttn
spring.datasource.password=ttn
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.default_schema=ibansys_ttn
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.open-in-view=false

app.log.dir=logs

signature.outputDir=C:/tempOC/signature-output
signature.keystorePath=C:/tempOC/keystore/signature.p12
signature.keystorePassword=changeit
signature.keyAlias=mykey
signature.keyPassword=changeit

#app.log.dir=src/main/resources/logs

signature.recipients=banque@test.com
signature.sourceTable=SIGNATURE.DETAIL_OBLIG_CAUT@DBLINK_SIGNATURE